### ISSUE TITLE
Future of this plugin? 

### ISSUE THREAD

**Issue by roman-hatz-sluz** [yasudacloud/strapi-plugin-sso#54]
Hi 

Thanks a lot for this plugin, I am just testing some of the SSO features. 
Question: what are the plans for this plugin? 

https://docs.strapi.io/dev-docs/configurations/sso 
"To configure SSO on your application, you will need an EE license.."

**Comment by yasudacloud** [comment]
@roman-hatz-sluz 
Hi!

This plugin is different from the SSO provided by Strapi and was implemented by myself and other developers.

As mentioned in the README, if it is possible to obtain an EE license, I recommend doing so. The reason is to have official support in case of security issues or version upgrades.

We believe this plugin is useful in situations where purchasing an EE license is not possible or where security can be ensured at the infrastructure level.
Regarding this plugin, I believe it would be beneficial to enhance its security-related features. However, I have not been able to start on it due to a lack of time.

Did I answer your question?

**Comment by roman-hatz-sluz** [comment]
Yes. Thanks a lot.

**Comment by yasudacloud** [comment]
Thanks for your question!
